[tool.poetry]
name = "chatbot-backend"
version = "0.1.0"
description = ""
authors = ["KRISHNA DIPAYAN BHUNIA <krishnabhunia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
